name: Base Master call a reusable workflow 

on:
  push:
    branches:
      - master

jobs:
  call-workflow-passing-data:
    uses: vladmalynych/action-test/.github/workflows/reusable.yaml@master
    with:
      build_id: ${{ github.run_number }}
