name: Patch image name in action-update

on:
  push:
    branches:
      - master

jobs:
    patch_remote:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v3
            with:
              repository: 'vladmalynych/action-update'
              path: action-update
              fetch-depth: 0

          - name: Update Image Version in the related yaml
            uses: fjogeleit/yaml-update-action@main
            with:
              valueFile: 'manifests/some_manifest/deployment.yml'
              propertyPath: 'metadata.name'
              value: 'test'
              repository: vladmalynych/action-update
              branch: master
              targetBranch: master
              createPR: false
              message: 'Update Image Version'
              token: ${{ secrets.GITHUB_TOKEN }}
              workDir: action-update
