name: Reusable workflow example

on:
  workflow_call:
    inputs:
      build_id:
        required: true
        type: string

jobs:
  reusable_job:
    name: Run test action
    runs-on: ubuntu-latest
    steps:
      - name: Base action
        run: echo ${{ inputs.build_id }}
        shell: bash
